targets = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "warn"
ignore = [
    # time has a security vulnerability, but it isn't interesting to us
    "RUSTSEC-2020-0071",
    # failure crate has a bug and is unmaintained, but we are only using it
    # via build dependencies
    "RUSTSEC-2020-0036",
    "RUSTSEC-2019-0036",
    # atty has a security vulnerability, but it only affects windows in obscure configurations
    "RUSTSEC-2021-0145",
]

[licenses]
# This was changed to warn to work around mbedtls and mbedtls-sys-auto issues
# See https://github.com/EmbarkStudios/cargo-deny/issues/498
unlicensed = "warn"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
    "GPL-3.0",
    "LGPL-3.0",
]
deny = []
copyleft = "allow"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8

[[licenses.clarify]]
name = "mc-sgx-types"
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xb433aff8 }
]


[[licenses.clarify]]
name = "rs-libc"
expression = "MIT"
license-files = [
    { path = "LICENSE", hash = 0x7933df3c }
]

[bans]
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
# Because we have many path deps into mobilecoin, we implicitly have wildcards,
# and that's okay for now, until it's not a submodule anymore.
wildcards = "warn"
highlight = "all"
allow = []
deny = [
    # https://github.com/briansmith/ring/issues/774
    # Unfortunately, we can't ban ring right now, because `mc-common` turns on
    # rustls for sentry.
    # { name = "ring" },
]
skip = [
    # Workaround for path only dependencies,
    # https://github.com/EmbarkStudios/cargo-deny/issues/241
    # { name = "some/dev/only/path" },
]
skip-tree = [ ]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
