[package]
name = "mc-bomb-enclave-edl"
version = "4.0.2"
authors = ["MobileCoin"]
edition = "2021"
links = "bomb_enclave_edl"
license = "GPL-3.0"
rust-version = { workspace = true }

[build-dependencies]
mc-util-build-script = { path = "../../mobilecoin/util/build/script" }

cargo-emit = "0.2"
