---
name: dependabot validate

"on":
  pull_request:
    paths:
      - '.github/dependabot.yaml'
      - '.github/workflows/dependabot-validate.yaml'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: marocchino/validate-dependabot@v2
        id: validate
        with:
          path: .github/dependabot.yaml
